full_rebuild: true
name: Wakanda Studio
author: Wakanda SAS
url: http://wakanda.io
version: 0.1
repository: https://github.com/Wakanda/wakanda-studio
branch: gh-pages
encoding: utf-8
themes: 
    general: wakanda
    code: github
version: 1.3
encoding: utf-8
defaults:
  -
    values:
      layout: "index"
exclude: [
.git,
.gitignore,
README.md,
LICENSE
]
